# Generated by Django 4.0.6 on 2022-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('instagram', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('duracion', models.DateField()),
                ('trabajo_actual', models.BooleanField()),
                ('descripcion', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilidad', models.CharField(max_length=20)),
                ('descripcion_habilidad', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_idioma', models.CharField(max_length=10)),
                ('segundo_idioma', models.CharField(max_length=10)),
                ('tercer_idioma', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
