# Generated by Django 4.0.6 on 2022-08-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCaro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='nombre_experiencia',
            field=models.CharField(default='Some String', max_length=20),
        ),
    ]
