# Generated by Django 4.0.6 on 2022-08-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCaro', '0002_experiencia_nombre_experiencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesion',
        ),
    ]
