# Generated by Django 4.0.6 on 2022-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCaro', '0003_delete_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='nombre_experiencia',
            field=models.CharField(max_length=20),
        ),
    ]
